version: '3.8'
name: myapp

services:

  botit-app:
    container_name: botit-app
    image: ahmedsamir98/botit:##TAGS##
    restart: always
    networks:
      - myapp_botit-app_botit
    labels:
       name: "botit-app"


networks:
  myapp_botit-app_botit:
    external: true
