version: "3"

name: myapp

services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - botit-app_botit
    ports:
      - 3000:3000

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - /opt/monitor/config/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - botit-app_botit

  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - /opt/monitor/grafana_data:/var/lib/grafana
      - /opt/monitor/config/grafana.ini:/etc/grafana/grafana.ini
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    networks:
      - botit-app_botit

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /opt/monitor/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/monitor/config/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - botit-app_botit
    labels:
      name: "prometheus"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - botit-app_botit
    labels:
      name: "cadvisor"

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    networks:
      - botit-app_botit
    labels:
      name: "node-exporter"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - /opt/monitor/config/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    labels:
      name: "nginx"
    ports:
      - '80:80'
    networks:
      - botit-app_botit

networks:
  botit-app_botit:
    driver: bridge