global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    username: 'Prometheus'
    channel: '#botit-app'
    api_url: 'https://hooks.slack.com/services/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'