name: Python CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yml to remote server
        run: scp docker-compose.yaml ubuntu@44.202.254.50:/opt/

      - name: SSH into the server and deploy with Docker Compose
        run: |
          ssh ubuntu@44.202.254.50 "cd /opt/ && docker-compose up -d"

