name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Docker images
        run: |
          docker-compose -f path/to/your/docker-compose.yml build

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f path/to/your/docker-compose.yml up -d
