name: botit-app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  botit-app:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set env
        run: echo "DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ahmedsamir98/botit:${{ env.DATE }}

      
      # - name: Build Docker image
      #   run: docker build -t ahmedsamir98/botit:$(date +'%Y%m%d-%H%M') .
      
      # - name: Push Docker image
      #   run: docker push ahmedsamir98/botit:$(date +'%Y%m%d-%H%M')

      # - name: Set up SSH
      #   run: |
      #     env
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          
      - name: Update docker-compose.yaml
        run: |
          sed -i 's|image: ahmedsamir98/botit:##TAGS##|image: ahmedsamir98/botit:${{ env.DATE }}|g' docker-compose.yaml

      # - name: Copy docker-compose.yaml to remote server
      #   run: |
      #     scp docker-compose.yaml ubuntu@44.202.254.50:/opt/botit-app

      # - name: Copy Docker Compose file to remote server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: "${{ secrets.ARTIFACT_HOST }}"
      #     username: "${{ secrets.REMOTE_SERVER_USERNAME }}"
      #     key: "${{ secrets.SSH_PRIVATE_KEY }}"
      #     port: 22
      #     source: "docker-compose.yaml"
      #     target: "/opt/botit-app"

      - name: Copy Docker Compose file from deployment branch to remote server
        uses: appleboy/scp-action@master
        with:
          host: "${{ secrets.ARTIFACT_HOST }}"
          username: "${{ secrets.REMOTE_SERVER_USERNAME }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          port: 22
          source: "docker-compose.yaml"
          target: "/opt/botit-app"
          source_branch: "deployment"


      # - name: SSH into the server and deploy with Docker Compose 
      #   run: |
      #     ssh ubuntu@44.202.254.50 "cd /opt/botit-app && sudo docker compose up -d"

      - name: SSH into remote server and start Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.ARTIFACT_HOST }}"
          username: "${{ secrets.REMOTE_SERVER_USERNAME }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          port: 22
          script: |
            cd /opt/botit-app/
            sudo docker compose up -d
            
      # - name: Slack Notification
      #   uses: act10ns/slack@v1
      #   with: 
      #     status: ${{ job.status }}
      #     channel: '#botit-app'
      #     message: Teeeeeeeeeeeeeeeeeeeeest!!!!!!!!!!!!!
      #   if: always()

      - uses: 8398a7/action-slack@v3
        with:
          text: "Slack message text. Failure :no_entry:"
          status: ${{ job.status }}
          fields: message,commit,author,eventName,ref,workflow,job,took
          mention: 'here'
          if_mention: failure,cancelled
        if: always()
